# Generated by Django 5.0 on 2023-12-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_highwatermark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighWatermark',
        ),
    ]
