# Lista zagadek
riddles = [
    "kobieta podróżująca środkiem transportu, np. samolotem, pociągiem, statkiem",
    "emocjonalne uczucie łączące dwie osoby, oparte na zaufaniu, szacunku, trosce i oddaniu",
    "miejsce, w którym dzieci uczą się nowych rzeczy i poznają nauczycieli",
    "przyrząd do pisania, zazwyczaj wypełniony atramentem lub wkładem z tuszem",
    "zwierzę domowe, często towarzyszy człowiekowi, jest wierne i ma ogon",
    "budynek z wieloma książkami, gdzie ludzie mogą czytać lub wypożyczać książki",
    "napój, który powstaje z ziaren, zazwyczaj jest czarny i pobudza do działania",
    "owoc o zielonej skórce i miękkim miąższu, z dużą pestką w środku",
    "półkulisty przedmiot, który chroni przed deszczem, trzymany nad głową",
    "wodna roślina pływająca, znana z pięknych, białych lub różowych kwiatów",
    "miejsce, gdzie oglądamy filmy na dużym ekranie",
    "czterokołowy pojazd, który prowadzi kierowca",
    "wysokie drzewo iglaste, często kojarzone z zimą i świętami",
    "narzędzie ogrodnicze używane do kopania w ziemi",
    "okrągły owoc o cytrusowym smaku, często używany do soków",
    "urządzenie, które pokazuje czas i jest noszone na nadgarstku",
    "duży obiekt sportowy z trybunami, gdzie odbywają się zawody",
    "owoc o żółtej skórce i słodkim smaku, często jedzony w tropikach",
    "czarna substancja, z której robi się asfalt na drogi",
    "narzędzie z dwoma ostrymi ramionami, używane do cięcia papieru",
    "ciecz, którą pijemy dla nawodnienia, często bezbarwna i bez smaku",
    "latające urządzenie transportowe, używane do podróży powietrznych",
    "ubranie noszone na stopach wewnątrz butów, zapewnia komfort i ciepło",
    "mebel, na którym śpimy, zazwyczaj z materacem",
    "kuchenne urządzenie do podgrzewania jedzenia, często mikrofalowe",
    "mały, błyszczący owad, który świeci w nocy",
    "wyspę otaczają wodne przestrzenie",
    "górska forma terenu z bardzo stromymi stokami",
    "instrument muzyczny z białymi i czarnymi klawiszami",
    "część domu z oknem, która wpuszcza światło",
    "białe, zimne płatki spadające zimą z nieba",
    "kolorowy, duży ptak o długim ogonie i piórach na czubku głowy",
    "pierwszy posiłek dnia, jedzony rano",
    "gorąca gwiazda, wokół której krążą planety",
    "powierzchnia, po której ludzie chodzą wewnątrz budynku",
    "trzyzębne narzędzie kuchenne, którym jemy posiłki",
    "twarda skorupa chroniąca mózg w organizmie człowieka",
    "białe linie na drodze, wskazujące miejsca przejścia dla pieszych",
    "miejsce pracy strażaka z czerwonymi wozami",
    "mały, piszczący gryzoń, często żyjący w domach jako pupil",
    "tkanina, którą nosimy na szyi, by było cieplej w zimne dni",
    "znak drogowy wskazujący, gdzie można przejść przez jezdnię",
    "naczynie do pieczenia, do którego wlewamy ciasto na chleb",
    "małe, słodkie kulki wytwarzane przez pszczoły",
    "podłużny owoc o żółtej skórce, popularny w smoothie",
    "duże zwierzę z trąbą, żyjące głównie w Afryce i Azji",
    "narzędzie do mierzenia temperatury",
    "biała substancja, którą dodajemy do herbaty lub kawy",
    "góry pełne śniegu, po których ludzie zjeżdżają na nartach",
    "święto obchodzone 25 grudnia na pamiątkę narodzin Jezusa",
    "małe urządzenie mobilne do komunikacji i przeglądania internetu"
]

# Lista odpowiedzi
answers = [
    "pasażerka",
    "miłość",
    "szkoła",
    "długopis",
    "pies",
    "biblioteka",
    "kawa",
    "awokado",
    "parasol",
    "lilia",
    "kino",
    "samochód",
    "choinka",
    "łopata",
    "cytryna",
    "zegarek",
    "stadion",
    "banan",
    "asfalt",
    "nożyczki",
    "woda",
    "samolot",
    "skarpetka",
    "łóżko",
    "mikrofalówka",
    "świetlik",
    "wyspa",
    "góra",
    "pianino",
    "okno",
    "śnieg",
    "papuga",
    "śniadanie",
    "słońce",
    "podłoga",
    "widelec",
    "czaszka",
    "pasy",
    "remiza",
    "mysz",
    "szalik",
    "zebra",
    "forma",
    "miód",
    "banan",
    "słoń",
    "termometr",
    "cukier",
    "stok",
    "święta",
    "smartfon"
]
