CREATE DATABASE Z3;

DROP TABLE IF EXISTS OSOBA;

DROP TABLE IF EXISTS MIEJSCE_PRACY;

-- wiele osób moze mieć tą samą pracę, kluczem obcym jest zatem miejsce pracy
CREATE TABLE OSOBA (
    OSOBA_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30),
    SURNAME VARCHAR(30),
    SALARY DECIMAL(10,2),
    WORK_ID INT,
    FOREIGN KEY (WORK_ID) REFERENCES MIEJSCE_PRACY(PRACA_ID)
);

CREATE TABLE MIEJSCE_PRACY (
    PRACA_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30)
);


INSERT INTO OSOBA (NAME, SURNAME, SALARY, WORK_ID) VALUES ('John', 'Doe', 50000.00, 1);
INSERT INTO OSOBA (NAME, SURNAME, SALARY, WORK_ID) VALUES ('Holly', 'Doe', 50000.00, 1);

INSERT INTO MIEJSCE_PRACY (NAME) VALUES ('Office A');
INSERT INTO MIEJSCE_PRACY (NAME) VALUES ('Office B');

