import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3100/');
  await page.getByRole('textbox', { name: 'Todo Name' }).click();
  await page.getByRole('textbox', { name: 'Todo Name' }).fill('first todo');
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'University' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Health' }).click();
  await page.getByRole('combobox', { name: 'Priority' }).click();
  await page.getByRole('option', { name: 'Medium' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('first todo');
  await expect(page.getByRole('rowgroup')).toContainText('To Do');
  await expect(page.getByRole('rowgroup')).toContainText('Medium');
  await page.getByRole('textbox', { name: 'Todo Name' }).click();
  await page.getByRole('textbox', { name: 'Todo Name' }).fill('second todo');
  await page.getByRole('combobox', { name: 'Priority' }).click();
  await page.getByRole('option', { name: 'High' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Shopping' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Transportation' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Social media' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('second todo');
  await expect(page.getByRole('rowgroup')).toContainText('To Do');
  await expect(page.getByRole('rowgroup')).toContainText('High');
  await expect(page.getByRole('rowgroup')).toContainText('Shopping, Transportation, Social media');
  await page.getByRole('textbox', { name: 'Todo Name' }).click();
  await page.getByRole('textbox', { name: 'Todo Name' }).fill('third todo');
  await page.getByRole('combobox', { name: 'Priority' }).click();
  await page.getByRole('option', { name: 'Low' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Transportation' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Recreation' }).click();
  await page.getByRole('combobox', { name: 'Tags' }).click();
  await page.getByRole('option', { name: 'Personal' }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('third todo');
  await expect(page.getByRole('rowgroup')).toContainText('To Do');
  await expect(page.getByRole('rowgroup')).toContainText('Low');
  await expect(page.getByRole('rowgroup')).toContainText('Transportation, Recreation, Personal');
  await page.getByRole('row', { name: 'second todo To Do High' }).getByLabel('Edit').click();
  await page.getByText('To Do').nth(1).click();
  await page.getByRole('option', { name: 'In Progress' }).click();
  await page.getByText('High').click();
  await page.getByRole('option', { name: 'Medium' }).click();
  await page.getByLabel('Save').click();
  await expect(page.getByRole('rowgroup')).toContainText('In Progress');
  await expect(page.getByRole('rowgroup')).toContainText('Medium');
  await page.getByRole('row', { name: 'third todo To Do Low' }).getByLabel('Edit').click();
  await page.getByText('To Do').nth(1).click();
  await page.getByRole('option', { name: 'Done' }).click();
  await page.getByText('Low').click();
  await page.getByRole('option', { name: 'Medium' }).click();
  await page.getByLabel('Save').click();
  await expect(page.getByRole('rowgroup')).toContainText('Done');
  await expect(page.getByRole('rowgroup')).toContainText('Medium');
  await page.getByRole('row', { name: 'first todo To Do Medium' }).getByLabel('Edit').click();
  await page.getByText('Medium').first().click();
  await page.getByRole('option', { name: 'High' }).click();
  await page.getByLabel('Cancel').click();
  await expect(page.getByRole('rowgroup')).toContainText('Medium');
  await page.getByRole('row', { name: 'second todo In Progress' }).getByLabel('Delete').click();
});